"""
Problem instances for local testing.

This module contains the problem sets without config validation dependencies.
"""

# TODO: the problems instances are all over the fucking place they're not associated with their right difficulty cuz i forgot which ones are which. good luck. Will fix later.
EASY_INSTANCES = [
    "psf__requests-5414",
    "django__django-13406", 
    "psf__requests-2317",
    "psf__requests-1921",
    "psf__requests-1724", 
    "psf__requests-1766",
    "psf__requests-1142",
    "pylint-dev__pylint-4970",
    "pylint-dev__pylint-6903",
    "pylint-dev__pylint-7277",
    "pydata__xarray-6461",
    "pydata__xarray-4075",
    "pydata__xarray-4629",
    "pydata__xarray-4094",
    "pydata__xarray-4356",
    "django__django-14493",
    "django__django-14376", 
    "matplotlib__matplotlib-25479",
    "django__django-14752",
    "sympy__sympy-23534",
    "sympy__sympy-18189",
    "matplotlib__matplotlib-24149",
    "astropy__astropy-13033",
    "astropy__astropy-13398",
    "psf__requests-6028",
    "psf__requests-2931",
    "pydata__xarray-2905",
    "pydata__xarray-3095",
    "pydata__xarray-4687",
    "pydata__xarray-4695",
    "pydata__xarray-4966",
    "pydata__xarray-6721",
    "pydata__xarray-6938",
    "pydata__xarray-7229",
    "pydata__xarray-7233",
]

MEDIUM_INSTANCES = [
    "pylint-dev__pylint-4661",
    "pylint-dev__pylint-6528",
    "pylint-dev__pylint-6386",
    "pylint-dev__pylint-7080",
    "pylint-dev__pylint-4604",
    "pydata__xarray-2905",
    "psf__requests-6028",
    "psf__requests-2931",
    "pydata__xarray-7233",
    "pydata__xarray-3095",
    "pydata__xarray-4687",
    "pydata__xarray-6938",
    "pydata__xarray-7229",
    "pydata__xarray-4695",
    "pydata__xarray-4966",
    "pydata__xarray-6721",
    "astropy__astropy-13033",
    "django__django-13279",
    "astropy__astropy-13579",
    "astropy__astropy-14369",
]

HARD_INSTANCES = [
    "django__django-15957",
    "pydata__xarray-3993", 
    "pylint-dev__pylint-4551",
    "pylint-dev__pylint-8898",
    "astropy__astropy-13398",
    "astropy__astropy-14369",
    "astropy__astropy-13579",
    "django__django-11885",
    "django__django-11138",
    "django__django-11400"
]

SCREENER_INSTANCES = [
    "astropy__astropy-14309",
    "django__django-11119",
    "psf__requests-5414",
    "psf__requests-6028",  
    "pylint-dev__pylint-7277",
]

TEST_SCREENER_INSTANCES = [
    "astropy__astropy-14309",
    "django__django-11119",
    "psf__requests-5414",
    "psf__requests-6028",
    "pylint-dev__pylint-7277",
]

VALIDATOR_EASY_INSTANCES = [
    "django__django-12209",
    "django__django-14315",
    "sympy__sympy-20916",
    "pytest-dev__pytest-5809",
    "astropy__astropy-7166",
    "django__django-14752",
    "django__django-14373",
    "sympy__sympy-15875",
    "pallets__flask-5014",
    "django__django-13410",
    "sympy__sympy-16886",
    "sympy__sympy-16450",
    "django__django-13023",
    "django__django-12308",
    "sympy__sympy-24562",
    "django__django-13406",
    "pytest-dev__pytest-10081",
    "pytest-dev__pytest-7432",
    "django__django-11820",
    "pytest-dev__pytest-5262",
]

VALIDATOR_MEDIUM_INSTANCES = [
    "django__django-10973",
    "pylint-dev__pylint-4661",
    "django__django-16877",
    "django__django-14672",
    "pylint-dev__pylint-4604",
    "sympy__sympy-24443",
    "astropy__astropy-7671",
    "pylint-dev__pylint-6386",
    "sympy__sympy-24213",
    "pytest-dev__pytest-7571",
    "sympy__sympy-23262",
    "sympy__sympy-15599",
    "django__django-13401",
    "sympy__sympy-20428",
    "pytest-dev__pytest-7236",
    "astropy__astropy-14539",
    "sympy__sympy-13798",
    "django__django-15252",
    "django__django-12273",
    "sympy__sympy-20438"
]

VALIDATOR_HARD_INSTANCES = [
    "pylint-dev__pylint-4551",
    "pylint-dev__pylint-8898",
    "sphinx-doc__sphinx-9229",
    "django__django-10554",
    "django__django-11885",
    "sympy__sympy-13852",
    "sympy__sympy-12489",
    "sympy__sympy-17630",
    "sympy__sympy-16597",
    "sympy__sympy-18199"
]